make:
	gcc main.cpp -o gdb_example

gdb: make
	gdb ./gdb_example
	# (gdb) break main.cpp:5
	# (gdb) break main
	# (gdb) run
	# (gdb) step
	# (gdb) finish
	# (gdb) next
	# (gdb) info locals
	# (gdb) print x
	# (gdb) continue
