install-pwgen:
	./scripts/install-pwgen.sh
.PONY: install-pwgen

generate-vault-password-file:
	./scripts/generate-vault-password-file.sh
.PONY: generate-vault-password-file

create-secrets-file:
	./scripts/create-secrets-file.sh
.PONY: create-secrets-file

view-secrets-file:
	./scripts/view-secrets-file.sh
.PONY: view-secrets-file
